package store

import (
	"context"
	"fmt"
	"strings"
)

var migrationStatements = []string{
	`create table if not exists schema_migrations (
		name text primary key,
		version integer not null,
		updated_at timestamptz not null default now()
	)`,
	`create table if not exists platform_users (
		id bigserial primary key,
		email varchar(320) unique,
		password_hash text,
		display_name varchar(128),
		role varchar(32) not null default 'user',
		status varchar(32) not null default 'active',
		plan varchar(32),
		notes text,
		created_by_user_id bigint references platform_users(id),
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now(),
		last_seen_at timestamptz,
		disabled_at timestamptz
	)`,
	`create index if not exists ix_platform_users_status_role on platform_users(status, role)`,
	`insert into platform_users(email, display_name, role, status)
	 values ('platform@oaix.local', 'Platform Bootstrap', 'admin', 'active')
	 on conflict (email) do update
	 set role = case when platform_users.role = '' then excluded.role else platform_users.role end,
	     status = case when platform_users.status in ('deleted', '') then excluded.status else platform_users.status end,
	     updated_at = now()`,
	`create table if not exists api_keys (
		id bigserial primary key,
		user_id bigint references platform_users(id) on delete cascade,
		kind varchar(32) not null default 'user',
		name varchar(128) not null,
		role varchar(32) not null default 'user',
		key_prefix varchar(32) not null,
		key_hash varchar(128) not null unique,
		scopes jsonb,
		last_used_at timestamptz,
		expires_at timestamptz,
		revoked_at timestamptz,
		created_by_user_id bigint references platform_users(id),
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now()
	)`,
	`create index if not exists ix_api_keys_user_active on api_keys(user_id, revoked_at, expires_at)`,
	`create index if not exists ix_api_keys_kind_role on api_keys(kind, role)`,
	`create table if not exists codex_tokens (
		id serial primary key,
		email varchar(320),
		account_id varchar(128),
		id_token text,
		access_token text,
		refresh_token text not null,
		refresh_token_aliases jsonb,
		merged_into_token_id integer,
		type varchar(32) not null default 'codex',
		last_refresh timestamptz,
		expired timestamptz,
		recovery jsonb,
		raw_payload jsonb,
		plan_type varchar(32),
		remark text,
		source_file varchar(512),
		is_active boolean not null default true,
		cooldown_until timestamptz,
		disabled_at timestamptz,
		share_enabled boolean not null default false,
		share_status varchar(32) not null default 'private',
		share_disabled_reason text,
		share_enabled_at timestamptz,
		share_disabled_at timestamptz,
		marketplace_price_bps integer,
		marketplace_price_updated_at timestamptz,
		marketplace_price_source varchar(64) not null default 'owner_default',
		last_used_at timestamptz,
		last_error text,
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now()
	)`,
	`create index if not exists ix_codex_tokens_active_ready on codex_tokens (is_active, cooldown_until, last_used_at, id) where merged_into_token_id is null`,
	`create index if not exists ix_codex_tokens_account_id on codex_tokens (account_id)`,
	`create index if not exists ix_codex_tokens_plan_type on codex_tokens (plan_type)`,
	`create index if not exists ix_codex_tokens_refresh_token on codex_tokens (refresh_token)`,
	`alter table codex_tokens alter column type set default 'codex'`,
	`update codex_tokens set type = 'codex' where type is null`,
	`alter table codex_tokens alter column type set not null`,
	`create table if not exists token_secrets (
		token_id integer primary key references codex_tokens(id) on delete cascade,
		access_token text,
		refresh_token text,
		id_token text,
		updated_at timestamptz not null default now()
	)`,
	`create table if not exists token_scopes (
		id serial primary key,
		token_id integer not null references codex_tokens(id) on delete cascade,
		scope varchar(128) not null,
		model varchar(128) not null default '*',
		created_at timestamptz not null default now(),
		unique(token_id, scope, model)
	)`,
	`create index if not exists ix_token_scopes_scope_model on token_scopes (scope, model)`,
	`create table if not exists token_refresh_history (
		id bigserial primary key,
		token_id integer not null references codex_tokens(id) on delete cascade,
		refresh_token_hash varchar(64) not null,
		seen_at timestamptz not null default now(),
		unique(token_id, refresh_token_hash)
	)`,
	`create index if not exists ix_token_refresh_history_hash on token_refresh_history (refresh_token_hash)`,
	`create table if not exists codex_token_scoped_cooldowns (
		id serial primary key,
		token_id integer not null references codex_tokens(id) on delete cascade,
		scope varchar(128) not null,
		cooldown_until timestamptz not null,
		last_error text,
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now(),
		unique(token_id, scope)
	)`,
	`create index if not exists ix_codex_token_scoped_cooldowns_scope on codex_token_scoped_cooldowns (scope, cooldown_until)`,
	`create table if not exists gateway_request_logs (
		id serial primary key,
		request_id varchar(64) not null unique,
		endpoint varchar(64) not null,
		model varchar(128),
		model_name varchar(128),
		is_stream boolean not null default false,
		status_code integer,
		success boolean,
		attempt_count integer not null default 0,
		token_id integer,
		account_id varchar(128),
		client_ip varchar(64),
		user_agent varchar(512),
		started_at timestamptz not null default now(),
		finished_at timestamptz,
		first_token_at timestamptz,
		ttft_ms integer,
		duration_ms integer,
		timing_spans jsonb,
		input_tokens integer,
		cached_input_tokens integer,
		output_tokens integer,
		total_tokens integer,
		estimated_cost_usd double precision,
		request_payload_hash varchar(64),
		upstream_payload_hash varchar(64),
		prompt_template_hash varchar(64),
		prompt_dynamic_hash varchar(64),
		prompt_cache_source varchar(64),
		prompt_cache_key_hash varchar(64),
		prompt_cache_retention_requested varchar(32),
		prompt_cache_retention_sent varchar(32),
		session_id_hash varchar(64),
		session_id_source varchar(32),
		previous_response_id_hash varchar(64),
		upstream_response_id varchar(128),
		cache_hit_ratio double precision,
		cache_affinity_result varchar(64),
		cache_affinity_lane_index integer,
		prompt_cache_trace jsonb,
		selection_mode varchar(32),
		caller_owner_user_id bigint,
		error_message text,
		analytics_recorded_at timestamptz
	)`,
	`create index if not exists ix_gateway_request_logs_started_at on gateway_request_logs (started_at desc)`,
	`create index if not exists ix_gateway_request_logs_finished_at on gateway_request_logs (finished_at desc)`,
	`create index if not exists ix_gateway_request_logs_token_id on gateway_request_logs (token_id)`,
	`create index if not exists ix_gateway_request_logs_model_name on gateway_request_logs (model_name)`,
	`create table if not exists gateway_request_attempts (
		id bigserial primary key,
		request_id varchar(64) not null,
		gateway_request_log_id bigint,
		attempt_index integer not null,
		owner_user_id bigint not null references platform_users(id),
		selection_mode varchar(32),
		caller_owner_user_id bigint references platform_users(id),
		exclude_owner_user_id bigint references platform_users(id),
		token_id bigint,
		token_owner_user_id bigint references platform_users(id),
		endpoint varchar(64),
		model varchar(128),
		started_at timestamptz not null,
		finished_at timestamptz,
		duration_ms integer,
		status_code integer,
		success boolean,
		retry boolean,
		outcome varchar(64),
		deactivated boolean not null default false,
		cooldown_until timestamptz,
		error_code varchar(128),
		error_message_excerpt text,
		error_body_hash varchar(64),
		claim_id bigint,
		candidate_count integer,
		ready_tokens integer,
		snapshot_version bigint,
		created_at timestamptz not null default now()
	)`,
	`create table if not exists gateway_request_log_partitions (
		partition_date date primary key,
		table_name varchar(128) not null unique,
		started_at timestamptz not null,
		finished_at timestamptz not null,
		created_at timestamptz not null default now()
	)`,
	`create table if not exists gateway_request_hourly_stats (
		id serial primary key,
		bucket_start timestamptz not null,
		model_name varchar(128) not null default '',
		request_count bigint not null default 0,
		success_count bigint not null default 0,
		failure_count bigint not null default 0,
		streaming_count bigint not null default 0,
		input_tokens bigint not null default 0,
		cached_input_tokens bigint not null default 0,
		output_tokens bigint not null default 0,
		total_tokens bigint not null default 0,
		estimated_cost_usd double precision not null default 0,
		ttft_ms_sum bigint not null default 0,
		ttft_count bigint not null default 0,
		duration_ms_sum bigint not null default 0,
		duration_count bigint not null default 0,
		updated_at timestamptz not null default now(),
		unique(bucket_start, model_name)
	)`,
	`create table if not exists gateway_request_token_costs (
		token_id integer primary key,
		request_count bigint not null default 0,
		estimated_cost_usd double precision not null default 0,
		updated_at timestamptz not null default now()
	)`,
	`create table if not exists gateway_settings (
		key varchar(128) primary key,
		value jsonb,
		updated_at timestamptz not null default now()
	)`,
	`create table if not exists user_settings (
		owner_user_id bigint not null references platform_users(id) on delete cascade,
		key varchar(128) not null,
		value jsonb,
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now(),
		primary key(owner_user_id, key)
	)`,
	`create index if not exists ix_user_settings_owner_updated on user_settings(owner_user_id, updated_at desc)`,
	`create table if not exists token_runtime_state (
		token_id integer primary key references codex_tokens(id) on delete cascade,
		active_streams integer not null default 0,
		cooldown_until timestamptz,
		disabled_reason text,
		failure_streak integer not null default 0,
		last_success_at timestamptz,
		last_failure_at timestamptz,
		updated_at timestamptz not null default now()
	)`,
	`create table if not exists token_state_events (
		id bigserial primary key,
		token_id integer not null,
		event_type varchar(64) not null,
		reason text,
		cooldown_until timestamptz,
		created_at timestamptz not null default now()
	)`,
	`create index if not exists ix_token_state_events_token_created on token_state_events (token_id, created_at desc)`,
	`alter table token_state_events add column if not exists request_id varchar(64)`,
	`alter table token_state_events add column if not exists gateway_request_log_id bigint`,
	`alter table token_state_events add column if not exists gateway_request_attempt_id bigint`,
	`alter table token_state_events add column if not exists endpoint varchar(64)`,
	`alter table token_state_events add column if not exists model varchar(128)`,
	`alter table token_state_events add column if not exists status_code integer`,
	`alter table token_state_events add column if not exists selection_mode varchar(32)`,
	`alter table token_state_events add column if not exists caller_owner_user_id bigint references platform_users(id)`,
	`alter table token_state_events add column if not exists previous_is_active boolean`,
	`alter table token_state_events add column if not exists next_is_active boolean`,
	`alter table token_state_events add column if not exists metadata jsonb`,
	`create table if not exists request_log_outbox (
		id bigserial primary key,
		request_id varchar(64) not null,
		payload jsonb not null,
		attempt_count integer not null default 0,
		next_attempt_at timestamptz not null default now(),
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now()
	)`,
	`create index if not exists ix_request_log_outbox_next_attempt on request_log_outbox (next_attempt_at, id)`,
	`create table if not exists prompt_affinity_lanes (
		prompt_key_hash varchar(128) primary key,
		primary_token_id integer,
		secondary_token_ids jsonb,
		marketplace_price_locks jsonb,
		policy_version integer not null default 1,
		expires_at timestamptz not null,
		updated_at timestamptz not null default now()
	)`,
	`create index if not exists ix_prompt_affinity_lanes_expires_at on prompt_affinity_lanes (expires_at)`,
	`create index if not exists ix_prompt_affinity_lanes_primary_token on prompt_affinity_lanes (primary_token_id)`,
	`create table if not exists response_owner_bindings (
		response_id_hash varchar(128) primary key,
		token_id integer not null,
		marketplace_price_bps integer,
		marketplace_price_source varchar(64),
		marketplace_price_locked_at timestamptz,
		marketplace_price_contract_key varchar(128),
		expires_at timestamptz not null,
		updated_at timestamptz not null default now()
	)`,
	`create index if not exists ix_response_owner_bindings_expires_at on response_owner_bindings (expires_at)`,
	`create table if not exists token_import_jobs (
		id serial primary key,
		status varchar(32) not null default 'queued',
		import_queue_position varchar(16) not null default 'front',
		payloads jsonb not null,
		total_count integer not null default 0,
		processed_count integer not null default 0,
		created_count integer not null default 0,
		updated_count integer not null default 0,
		skipped_count integer not null default 0,
		failed_count integer not null default 0,
		yielded_to_response_traffic_count integer not null default 0,
		response_traffic_timeout_count integer not null default 0,
		created_items jsonb,
		updated_items jsonb,
		skipped_items jsonb,
		failed_items jsonb,
		last_error text,
		submitted_at timestamptz not null default now(),
		started_at timestamptz,
		heartbeat_at timestamptz,
		finished_at timestamptz
	)`,
	`alter table token_import_jobs add column if not exists processed_count integer`,
	`alter table token_import_jobs add column if not exists created_count integer`,
	`alter table token_import_jobs add column if not exists updated_count integer`,
	`alter table token_import_jobs add column if not exists skipped_count integer`,
	`alter table token_import_jobs add column if not exists failed_count integer`,
	`update token_import_jobs
		set processed_count = coalesce(processed_count, 0),
		    created_count = coalesce(created_count, 0),
		    updated_count = coalesce(updated_count, 0),
		    skipped_count = coalesce(skipped_count, 0),
		    failed_count = coalesce(failed_count, 0)
		where processed_count is null
		   or created_count is null
		   or updated_count is null
		   or skipped_count is null
		   or failed_count is null`,
	`alter table token_import_jobs alter column processed_count set default 0`,
	`alter table token_import_jobs alter column created_count set default 0`,
	`alter table token_import_jobs alter column updated_count set default 0`,
	`alter table token_import_jobs alter column skipped_count set default 0`,
	`alter table token_import_jobs alter column failed_count set default 0`,
	`alter table token_import_jobs alter column processed_count set not null`,
	`alter table token_import_jobs alter column created_count set not null`,
	`alter table token_import_jobs alter column updated_count set not null`,
	`alter table token_import_jobs alter column skipped_count set not null`,
	`alter table token_import_jobs alter column failed_count set not null`,
	`alter table token_import_jobs add column if not exists yielded_to_response_traffic_count integer`,
	`alter table token_import_jobs add column if not exists response_traffic_timeout_count integer`,
	`update token_import_jobs
		set yielded_to_response_traffic_count = coalesce(yielded_to_response_traffic_count, 0),
		    response_traffic_timeout_count = coalesce(response_traffic_timeout_count, 0)
		where yielded_to_response_traffic_count is null
		   or response_traffic_timeout_count is null`,
	`alter table token_import_jobs alter column yielded_to_response_traffic_count set default 0`,
	`alter table token_import_jobs alter column response_traffic_timeout_count set default 0`,
	`alter table token_import_jobs alter column yielded_to_response_traffic_count set not null`,
	`alter table token_import_jobs alter column response_traffic_timeout_count set not null`,
	`create table if not exists token_import_items (
		id serial primary key,
		job_id integer not null references token_import_jobs(id) on delete cascade,
		item_index integer not null,
		status varchar(32) not null default 'queued',
		refresh_token_hash varchar(64),
		encrypted_payload text,
		payload jsonb,
		validated_payload jsonb,
		token_id integer,
		action varchar(32),
		error_message text,
		validation_ms integer,
		publish_ms integer,
		import_validate_ms integer,
		import_publish_ms integer,
		validation_started_at timestamptz,
		validation_finished_at timestamptz,
		published_at timestamptz,
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now(),
		unique(job_id, item_index)
	)`,
	`alter table token_import_items add column if not exists status varchar(32)`,
	`update token_import_items set status = 'queued' where status is null`,
	`alter table token_import_items alter column status set default 'queued'`,
	`alter table token_import_items alter column status set not null`,
	`alter table token_import_items add column if not exists matched_existing_token_id bigint`,
	`alter table token_import_items add column if not exists publish_attempted boolean not null default false`,
	`alter table token_import_items add column if not exists publish_skipped_reason varchar(128)`,
	`alter table token_import_items add column if not exists reactivated boolean not null default false`,
	`alter table token_import_items add column if not exists previous_is_active boolean`,
	`alter table token_import_items add column if not exists next_is_active boolean`,
	`alter table token_import_items add column if not exists previous_disabled_at timestamptz`,
	`alter table token_import_items add column if not exists next_disabled_at timestamptz`,
	`alter table token_import_items add column if not exists refresh_error_code varchar(128)`,
	`alter table token_import_items add column if not exists refresh_error_message_excerpt text`,
	`create table if not exists admin_audit_logs (
		id bigserial primary key,
		action varchar(128) not null,
		actor varchar(128),
		target_type varchar(64),
		target_id varchar(128),
		payload jsonb,
		created_at timestamptz not null default now()
	)`,
	`create table if not exists admin_api_keys (
		id bigserial primary key,
		name varchar(128) not null,
		key_hash varchar(64) not null unique,
		role varchar(32) not null default 'admin',
		created_by varchar(128),
		created_at timestamptz not null default now(),
		last_used_at timestamptz,
		revoked_at timestamptz
	)`,
	`create index if not exists ix_admin_api_keys_revoked_at on admin_api_keys (revoked_at)`,
	`create table if not exists admin_idempotency_keys (
		key varchar(160) primary key,
		method varchar(16) not null,
		path text not null,
		request_hash varchar(64) not null,
		status_code integer not null,
		response jsonb not null,
		created_at timestamptz not null default now(),
		expires_at timestamptz not null
	)`,
	`create index if not exists ix_admin_idempotency_keys_expires_at on admin_idempotency_keys (expires_at)`,
	`create table if not exists openai_oauth_sessions (
		session_id varchar(64) primary key,
		state varchar(128) not null unique,
		code_verifier text not null,
		redirect_uri text not null,
		import_queue_position varchar(16) not null default 'front',
		status varchar(32) not null default 'pending',
		import_job_id integer references token_import_jobs(id) on delete set null,
		error_message text,
		created_at timestamptz not null default now(),
		expires_at timestamptz not null,
		updated_at timestamptz not null default now()
	)`,
	`create index if not exists ix_openai_oauth_sessions_status on openai_oauth_sessions (status, expires_at)`,
	`create table if not exists token_quota_snapshots (
		id bigserial primary key,
		token_id integer not null references codex_tokens(id) on delete cascade,
		snapshot jsonb,
		plan_type varchar(32),
		error_message text,
		fetched_at timestamptz not null default now()
	)`,
	`create index if not exists ix_token_quota_snapshots_token_fetched on token_quota_snapshots (token_id, fetched_at desc)`,
	`insert into api_keys(user_id, kind, name, role, key_prefix, key_hash, last_used_at, revoked_at, created_at, updated_at)
	 select (select id from platform_users where email = 'platform@oaix.local'),
	        'service', name, role, left(key_hash, 24), key_hash, last_used_at, revoked_at, created_at, now()
	 from admin_api_keys
	 on conflict (key_hash) do nothing`,
	`alter table codex_tokens add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table codex_tokens add column if not exists share_enabled boolean not null default false`,
	`alter table codex_tokens add column if not exists share_status varchar(32) not null default 'private'`,
	`alter table codex_tokens add column if not exists share_disabled_reason text`,
	`alter table codex_tokens add column if not exists share_enabled_at timestamptz`,
	`alter table codex_tokens add column if not exists share_disabled_at timestamptz`,
	`alter table codex_tokens add column if not exists marketplace_price_bps integer`,
	`alter table codex_tokens add column if not exists marketplace_price_updated_at timestamptz`,
	`alter table codex_tokens add column if not exists marketplace_price_source varchar(64) not null default 'owner_default'`,
	`update codex_tokens set marketplace_price_source = 'owner_default' where marketplace_price_source is null or btrim(marketplace_price_source) = ''`,
	`alter table codex_tokens alter column marketplace_price_source set default 'owner_default'`,
	`alter table codex_tokens alter column marketplace_price_source set not null`,
	`alter table token_secrets add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table token_scopes add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table token_refresh_history add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table codex_token_scoped_cooldowns add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table token_runtime_state add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table token_state_events add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table token_import_jobs add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table token_import_items add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table openai_oauth_sessions add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table token_quota_snapshots add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table gateway_request_logs add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table gateway_request_logs add column if not exists api_key_id bigint references api_keys(id)`,
	`alter table gateway_request_logs add column if not exists token_owner_user_id bigint references platform_users(id)`,
	`alter table gateway_request_logs add column if not exists selection_mode varchar(32)`,
	`alter table gateway_request_logs add column if not exists caller_owner_user_id bigint references platform_users(id)`,
	`alter table gateway_request_token_costs add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table gateway_request_hourly_stats add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table gateway_request_hourly_stats add column if not exists cached_input_tokens bigint not null default 0`,
	`alter table gateway_request_hourly_stats alter column request_count type bigint using request_count::bigint`,
	`alter table gateway_request_hourly_stats alter column success_count type bigint using success_count::bigint`,
	`alter table gateway_request_hourly_stats alter column failure_count type bigint using failure_count::bigint`,
	`alter table gateway_request_hourly_stats alter column streaming_count type bigint using streaming_count::bigint`,
	`alter table gateway_request_hourly_stats alter column input_tokens type bigint using input_tokens::bigint`,
	`alter table gateway_request_hourly_stats alter column cached_input_tokens type bigint using cached_input_tokens::bigint`,
	`alter table gateway_request_hourly_stats alter column output_tokens type bigint using output_tokens::bigint`,
	`alter table gateway_request_hourly_stats alter column total_tokens type bigint using total_tokens::bigint`,
	`alter table gateway_request_hourly_stats alter column ttft_ms_sum type bigint using ttft_ms_sum::bigint`,
	`alter table gateway_request_hourly_stats alter column ttft_count type bigint using ttft_count::bigint`,
	`alter table gateway_request_hourly_stats alter column duration_ms_sum type bigint using duration_ms_sum::bigint`,
	`alter table gateway_request_hourly_stats alter column duration_count type bigint using duration_count::bigint`,
	`alter table gateway_request_token_costs alter column request_count type bigint using request_count::bigint`,
	`alter table prompt_affinity_lanes add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table prompt_affinity_lanes add column if not exists marketplace_price_locks jsonb`,
	`alter table response_owner_bindings add column if not exists owner_user_id bigint references platform_users(id)`,
	`alter table response_owner_bindings add column if not exists marketplace_price_bps integer`,
	`alter table response_owner_bindings add column if not exists marketplace_price_source varchar(64)`,
	`alter table response_owner_bindings add column if not exists marketplace_price_locked_at timestamptz`,
	`alter table response_owner_bindings add column if not exists marketplace_price_contract_key varchar(128)`,
	`alter table admin_audit_logs add column if not exists actor_user_id bigint references platform_users(id)`,
	`alter table admin_audit_logs add column if not exists actor_api_key_id bigint references api_keys(id)`,
	`alter table admin_audit_logs add column if not exists actor_role varchar(32)`,
	`alter table admin_audit_logs add column if not exists target_user_id bigint references platform_users(id)`,
	`alter table admin_audit_logs add column if not exists ip varchar(64)`,
	`alter table admin_audit_logs add column if not exists user_agent varchar(512)`,
	`update codex_tokens set owner_user_id = (select id from platform_users where email = 'platform@oaix.local') where owner_user_id is null`,
	`update token_import_jobs set owner_user_id = (select id from platform_users where email = 'platform@oaix.local') where owner_user_id is null`,
	`update token_import_items i set owner_user_id = coalesce(j.owner_user_id, (select id from platform_users where email = 'platform@oaix.local'))
	 from token_import_jobs j
	 where j.id = i.job_id and i.owner_user_id is null`,
	`update token_secrets s set owner_user_id = t.owner_user_id from codex_tokens t where t.id = s.token_id and s.owner_user_id is null`,
	`update token_scopes s set owner_user_id = t.owner_user_id from codex_tokens t where t.id = s.token_id and s.owner_user_id is null`,
	`update token_refresh_history h set owner_user_id = t.owner_user_id from codex_tokens t where t.id = h.token_id and h.owner_user_id is null`,
	`update codex_token_scoped_cooldowns c set owner_user_id = t.owner_user_id from codex_tokens t where t.id = c.token_id and c.owner_user_id is null`,
	`update token_runtime_state r set owner_user_id = t.owner_user_id from codex_tokens t where t.id = r.token_id and r.owner_user_id is null`,
	`update token_state_events e set owner_user_id = t.owner_user_id from codex_tokens t where t.id = e.token_id and e.owner_user_id is null`,
	`update token_quota_snapshots q set owner_user_id = t.owner_user_id from codex_tokens t where t.id = q.token_id and q.owner_user_id is null`,
	`update gateway_request_hourly_stats set owner_user_id = (select id from platform_users where email = 'platform@oaix.local') where owner_user_id is null`,
	`update gateway_request_token_costs c set owner_user_id = t.owner_user_id from codex_tokens t where t.id = c.token_id and c.owner_user_id is null`,
	`alter table gateway_request_hourly_stats drop constraint if exists gateway_request_hourly_stats_bucket_start_model_name_key`,
	`alter table gateway_request_hourly_stats drop constraint if exists uq_gateway_request_hourly_stats_bucket_model`,
	`alter table gateway_request_hourly_stats alter column owner_user_id set not null`,
	`create unique index if not exists ux_gateway_request_hourly_stats_owner_bucket_model on gateway_request_hourly_stats(owner_user_id, bucket_start, model_name)`,
	`create index if not exists ix_codex_tokens_owner_active_ready on codex_tokens(owner_user_id, is_active, cooldown_until, last_used_at, id) where merged_into_token_id is null`,
	`create index if not exists ix_codex_tokens_owner_plan on codex_tokens(owner_user_id, plan_type)`,
	`create index if not exists ix_token_import_jobs_owner_submitted on token_import_jobs(owner_user_id, submitted_at desc)`,
	`create index if not exists ix_token_import_items_owner_job_status on token_import_items(owner_user_id, job_id, status)`,
	`create table if not exists sub2api_sync_targets (
		id bigserial primary key,
		name varchar(128) not null,
		base_url text not null,
		admin_key text not null,
		enabled boolean not null default true,
		owner_user_id bigint references platform_users(id),
		plan_filters text[] not null default '{}',
		token_status_filters text[] not null default array['available','cooling']::text[],
		target_group_ids bigint[] not null default '{}',
		target_group_names text[] not null default '{}',
		check_interval_seconds integer not null default 300,
		min_available integer not null default 10,
		top_up_batch_size integer not null default 10,
		account_concurrency integer not null default 10,
		account_priority integer not null default 50,
		proxy_id bigint not null default 0,
		auto_sync_new boolean not null default false,
		last_checked_at timestamptz,
		last_synced_at timestamptz,
		last_status varchar(32),
		last_error text,
		last_remote_count integer,
		last_synced_count integer not null default 0,
		last_run_id bigint,
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now()
	)`,
	`alter table sub2api_sync_targets add column if not exists token_status_filters text[] not null default array['available','cooling']::text[]`,
	`alter table sub2api_sync_targets add column if not exists account_concurrency integer not null default 10`,
	`alter table sub2api_sync_targets add column if not exists account_priority integer not null default 50`,
	`alter table sub2api_sync_targets add column if not exists proxy_id bigint not null default 0`,
	`create index if not exists ix_sub2api_sync_targets_enabled_check on sub2api_sync_targets(enabled, last_checked_at)`,
	`create table if not exists sub2api_sync_runs (
		id bigserial primary key,
		target_id bigint not null references sub2api_sync_targets(id) on delete cascade,
		trigger varchar(32) not null,
		status varchar(32) not null,
		remote_count integer not null default 0,
		threshold integer not null default 0,
		needed_count integer not null default 0,
		selected_count integer not null default 0,
		synced_count integer not null default 0,
		failed_count integer not null default 0,
		error_message text,
		started_at timestamptz not null default now(),
		finished_at timestamptz,
		details jsonb
	)`,
	`create index if not exists ix_sub2api_sync_runs_target_started on sub2api_sync_runs(target_id, started_at desc)`,
	`create table if not exists sub2api_sync_mappings (
		target_id bigint not null references sub2api_sync_targets(id) on delete cascade,
		token_id integer not null references codex_tokens(id) on delete cascade,
		remote_account_id bigint,
		last_run_id bigint references sub2api_sync_runs(id) on delete set null,
		status varchar(32) not null default 'synced',
		error_message text,
		created_at timestamptz not null default now(),
		updated_at timestamptz not null default now(),
		primary key(target_id, token_id)
	)`,
	`create index if not exists ix_sub2api_sync_mappings_token on sub2api_sync_mappings(token_id)`,
}

var onlineMigrationStatements = []string{
	`create index concurrently if not exists ix_gateway_request_logs_analytics_pending on gateway_request_logs (id) where analytics_recorded_at is null and finished_at is not null`,
	`create index concurrently if not exists ix_gateway_request_logs_token_cost on gateway_request_logs (token_id, estimated_cost_usd) where token_id is not null and estimated_cost_usd is not null`,
	`create index concurrently if not exists ix_gateway_request_logs_pending_token_cost on gateway_request_logs (token_id) include (estimated_cost_usd) where analytics_recorded_at is null and token_id is not null and estimated_cost_usd is not null`,
	`create index concurrently if not exists ix_gateway_request_logs_account_cost on gateway_request_logs (account_id, estimated_cost_usd) where account_id is not null and estimated_cost_usd is not null`,
	`create index concurrently if not exists ix_gateway_request_hourly_stats_bucket_start on gateway_request_hourly_stats (bucket_start desc)`,
	`create index concurrently if not exists ix_codex_tokens_shared_ready on codex_tokens (share_enabled, share_status, is_active, cooldown_until, last_used_at, id) where merged_into_token_id is null`,
	`create index concurrently if not exists ix_codex_tokens_marketplace_price_ready on codex_tokens (marketplace_price_bps, is_active, cooldown_until, last_used_at, id) where merged_into_token_id is null and share_enabled = true and share_status = 'active'`,
	`create index concurrently if not exists ix_gateway_request_logs_owner_started on gateway_request_logs(owner_user_id, started_at desc) where owner_user_id is not null`,
	`create index concurrently if not exists ix_gateway_request_logs_token_owner_started on gateway_request_logs(token_owner_user_id, started_at desc) where token_owner_user_id is not null`,
	`create index concurrently if not exists ix_gateway_request_attempts_request_attempt on gateway_request_attempts(request_id, attempt_index)`,
	`create index concurrently if not exists ix_gateway_request_attempts_token_started on gateway_request_attempts(token_id, started_at desc) where token_id is not null`,
	`create index concurrently if not exists ix_gateway_request_attempts_owner_started on gateway_request_attempts(owner_user_id, started_at desc)`,
	`create index concurrently if not exists ix_gateway_request_attempts_outcome_started on gateway_request_attempts(outcome, started_at desc)`,
	`create index concurrently if not exists ix_token_state_events_request_attempt on token_state_events(request_id, gateway_request_attempt_id) where request_id is not null`,
	`create index concurrently if not exists ix_token_import_items_existing_token on token_import_items(matched_existing_token_id) where matched_existing_token_id is not null`,
}

var downMigrationStatements = []string{
	`drop table if exists sub2api_sync_mappings`,
	`drop table if exists sub2api_sync_runs`,
	`drop table if exists sub2api_sync_targets`,
	`drop table if exists token_quota_snapshots`,
	`drop table if exists openai_oauth_sessions`,
	`drop table if exists admin_idempotency_keys`,
	`drop table if exists admin_api_keys`,
	`drop table if exists admin_audit_logs`,
	`drop table if exists token_import_items`,
	`drop table if exists token_import_jobs`,
	`drop table if exists response_owner_bindings`,
	`drop table if exists prompt_affinity_lanes`,
	`drop table if exists gateway_request_log_partitions`,
	`drop table if exists gateway_request_attempts`,
	`drop table if exists request_log_outbox`,
	`drop table if exists token_state_events`,
	`drop table if exists token_runtime_state`,
	`drop table if exists user_settings`,
	`drop table if exists token_refresh_history`,
	`drop table if exists token_scopes`,
	`drop table if exists token_secrets`,
	`delete from schema_migrations where name = 'oaix_go'`,
}

func (s *Store) Migrate(ctx context.Context) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	for index, statement := range migrationStatements {
		if _, err := tx.Exec(ctx, statement); err != nil {
			return fmt.Errorf("migration statement %d failed: %w\n%s", index+1, err, strings.TrimSpace(statement))
		}
	}
	if _, err := tx.Exec(ctx, `
		insert into schema_migrations(name, version, updated_at)
		values ('oaix_go', $1, now())
		on conflict (name) do update set version = excluded.version, updated_at = now()
	`, SchemaVersion); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return err
	}
	for index, statement := range onlineMigrationStatements {
		if _, err := s.pool.Exec(ctx, statement); err != nil {
			return fmt.Errorf("online migration statement %d failed: %w\n%s", index+1, err, strings.TrimSpace(statement))
		}
	}
	return nil
}

func (s *Store) MigrateDown(ctx context.Context) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	for index, statement := range downMigrationStatements {
		if _, err := tx.Exec(ctx, statement); err != nil {
			return fmt.Errorf("down migration statement %d failed: %w\n%s", index+1, err, strings.TrimSpace(statement))
		}
	}
	return tx.Commit(ctx)
}
